### PR TITLE
Fix for missing files

### PR DESCRIPTION
**Pull request by GeoDirk**
Hey Paul - your current Master won't compile as I didn't submit my
.csproj files.  This PR will fix that.

### CODE REVIEW

**Comment by pauldendulk** [comment]
I already added the changes that were missing in your previous PR. Am I missing something? According to AppVeyor the latest release builds: https://ci.appveyor.com/project/pauldendulk/mapsui

**Comment by GeoDirk** [comment]
You are missing the changes to the Samples/Mapsui.Samples.Common.Desktop/Mapsui.Samples.Common.Desktop.csproj file

**Comment by GeoDirk** [comment]
Without that, my new files are not part of the solution.  They just just part of the directory.

**Comment by GeoDirk** [comment]
The solution shouldn't build because of the line:

allSamples["Shapefile Hover/Info (Desktop)"] = ShapefileHoverInfoSample.CreateMap; 

actually doesn't exist since it is not part of the solution because of the missing .csproj changes.

```
        private static Dictionary<string, Func<Map>> DemoSamples()
        {
            var allSamples = Common.AllSamples.CreateList();
            // Append samples from Mapsui.Desktop
            allSamples["Shapefile (Desktop)"] = ShapefileSample.CreateMap;
            allSamples["Shapefile Hover/Info (Desktop)"] = ShapefileHoverInfoSample.CreateMap;
            allSamples["Tiles on disk (Desktop)"] = MapTilerSample.CreateMap;
            allSamples["WMS (Desktop)"] = WmsSample.CreateMap;
            return allSamples;
        }
```

**Comment by pauldendulk** [comment]
But how come the build server is building? Could you do s fresh clone to
check?

Paul

Op 17 mrt. 2018 14:41 schreef "GeoDirk" <notifications@github.com>:

The solution shouldn't build because of the line:

allSamples["Shapefile Hover/Info (Desktop)"] = ShapefileHoverInfoSample.
CreateMap;

actually doesn't exist since it is not part of the solution because of the
missing .csproj changes.

        private static Dictionary<string, Func<Map>> DemoSamples()
        {
            var allSamples = Common.AllSamples.CreateList();
            // Append samples from Mapsui.Desktop
            allSamples["Shapefile (Desktop)"] = ShapefileSample.CreateMap;
            allSamples["Shapefile Hover/Info (Desktop)"] =
ShapefileHoverInfoSample.CreateMap;
            allSamples["Tiles on disk (Desktop)"] = MapTilerSample.CreateMap;
            allSamples["WMS (Desktop)"] = WmsSample.CreateMap;
            return allSamples;
        }

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/pauldendulk/Mapsui/pull/350#issuecomment-373920941>,
or mute
the thread

**Comment by GeoDirk** [comment]
@pauldendulk 

Nevermind...I pulled down a fresh copy from the repo and yes not only does it compile but the new class file and all the associated other changes are indeed there.

I'm a SVN guy and not much of a Git person.  I'll get the hang of this eventually.  Glad the examples made it in.

You can close this PR out after reading this.

**Comment by pauldendulk** [comment]
Ok. All cleared up!

**Pull request closed without merging**
