### PR TITLE
Improved Shapefile demo on Master branch

### PR DESCRIPTION
**Pull request by GeoDirk**
Examples of:
- Using ThemeStyle to individually color selected features from a shapefile
- Hover layer to return info from city points
- Info layer to return country features on mouse click

### CODE REVIEW

**Comment by GeoDirk** [comment]
Created a new class file to supplement the original one with only the new demo features.

**Comment by GeoDirk** [comment]
After this is added, you can also close #266

**Comment by charlenni** [comment]
Sorry, @pauldendulk , but there isn't any new code. Did you merged this?

**Comment by pauldendulk** [comment]
I did not merge it yet. Looking at the compile error by AppVeyor.

**Comment by pauldendulk** [comment]
@GeoDirk You forgot to commit some csproj's but I'll merge anyway.

**Comment by pauldendulk** [comment]
@charlenni I had not merged yet.

**Pull request merged**
