### PR TITLE
Add rotation to Viewport.Transform

### PR DESCRIPTION
**Pull request by radderz**
Add rotation to Viewport.Transform. This will make the rotation occur around the centerpoint of the tranformation.

Added UWP rotation capability.

### CODE REVIEW

**Comment by radderz** [comment]
This fixes #292 and Adds rotation to UWP

**Comment by radderz** [comment]
@pauldendulk - Would be good if we can have this as part of 1.3.2-beta too and I'll see if the change breaks anything major.

**Comment by pauldendulk** [comment]
The distance check was removed. This prevented a sudden jump of the center of pinch. Why is this not necessary anymore?

In the past it showed when you were panning with two fingers and then lifted one of those fingers.

**Comment by radderz** [comment]
Hi Paul, its not need because I am not using the method that was used before which wasn't correct. This method looks at the translation x and y which doesn't matter if a single finger or multiple are down as its the relative movement that is respected. I have tested it on both mobile and pc and it works with all touch scenarios. 

I got the rotation about the right point, pan and zoom all working on the 3 platforms with these changes. And again managed to share the logic.

**Comment by pauldendulk** [comment]
@radderz I released 1.3.2-beta2 with your changes. https://www.nuget.org/packages/Mapsui/1.3.2-beta2

**Pull request merged**
