### PR TITLE
Extending Skia renderer to respect PenStrokeCap and PenStyle

### PR DESCRIPTION
**Pull request by charlenni**
Respect PenStrokeCap and PenStyle in Skia render. Perhaps it is a fine adjustment for line width in PenStyleExtension.

Styles should be refactored. They are not very consistent.

### CODE REVIEW

**Comment by pauldendulk** [comment]
Thank you very much!

**Comment by charlenni** [comment]
Yes, more or less. You could delete it.

What do we with the Opacity. @Kortdag is right, when he said, that ithis is inconsistent. Rename Opacity to BitmapOpacity will break old apps. Perhaps use Opacity when Color.A is 255?

**Comment by pauldendulk** [comment]
Let's discuss this further in the issue.

**Comment by radderz** [comment]
I mentioned what to do re opacity in the issue, its pretty easy, you just apply it to the color that you are using to draw the non bitmap symbol vs the color specified, i.e multiple the alpha of the color by the opactity.

**Comment by charlenni** [comment]
If I‘m right, Paul made a PR.

**Pull request merged**
