### PR TITLE
Several Geometry additions/changes

### PR DESCRIPTION
**Pull request by dirkdokter**
Non-breaking:
- Added Algorithms.Distance overload for two Geometries.Points (instead of 4 doubles).   
- Added method to get the segments (individual two-point lines) of a LineString.
- Added method to create a (closed) LineString from a LinearRing.

Breaking:
- LinearRing.IsClosed always returns true now, as a LinearRing is closed by definition, even if the StartPoint and EndPoint are not geometrically equal. **This might be breaking.**  Just remove this change if you think this can be a problem for anyone.

### CODE REVIEW

**Comment by charlenni** [comment]
Why do you deliver corners of BoundingBox in CCW? Is there a special reason for this?

**Comment by dirkdokter** [comment]
No specific reason, other than just being accustomed to it because we use CCW by default in several internal applications.

Is the convention in Mapsui CW?

**Comment by charlenni** [comment]
I don‘t know this. But Skia uses CW polygons for outer rings and CCW for inner rings. And Mapbox vector format do the same.

**Comment by dirkdokter** [comment]
Makes sense to change it to CW then. Done.

**Comment by pauldendulk** [comment]
About CW versus CCW. In my code there is this comment, that according to git history is written by me (can't remember). 

``` C#
// note: For Skia inner rings need to be clockwise and outer rings
// need to be counter clockwise (if this is the other way around it also
// seems to work)
// this is not a requirement of the OGC polygon.
```
So it think this means that the outer ring can be CCW if the inner ring is CW. Mapsui has no specific preference, but perhaps we should have some consistency in our interfaces. At this point I do not know what that should be. The OGC Simple Geometry specification also has no specific preference.

**Comment by pauldendulk** [comment]
The LinearRing.IsClosed should return false if begin and end are not the same. Why did you change this? For editing is also handy to have the same begin and end point. 

From your other functionality I can see you are working on editing, because you are adding exactly the feature I need (I am also working on editing).

**Comment by pauldendulk** [comment]
For what situation do you need a to transform a LinearRing to LineString?

**Comment by pauldendulk** [comment]
General remark. Note, that at some point we will start using NTS. This will impact these changes. In some situations you could check if NTS has the implementation you want to add. If not, then you could perhaps better add it as an extension method instead of a extra method to the geometry itself.

**Comment by charlenni** [comment]
Mapbox uses CW for exterior rings and CCW for interior rings. See [here](https://www.mapbox.com/vector-tiles/specification/#winding-order).

**Comment by pauldendulk** [comment]
Ah. Lets follow that.

**Comment by dirkdokter** [comment]
Thanks for merging.

> The LinearRing.IsClosed should return false if begin and end are not the same. Why did you change this? For editing is also handy to have the same begin and end point.

I changed this to always return True, as the LinearRing is simple and closed by definition:
https://github.com/pauldendulk/Mapsui/blob/222edcafc0197d3893426ecc1b868377561d106b/Mapsui.Geometries/LinearRing.cs#L25

I think my reasoning was as follows. Note that i'm not a mathematician, so please correct me if i'm wrong:

If a LinearRing is described/defined in that way, it's IsClosed property should always be true. Code that is using a LinearRing, or methods of LinearRing, should take into account that the first and last vertex are not necessarily the same.

I'm not sure what would be the most mathematically/topologically correct method. 
[Wikipedia ](https://en.wikipedia.org/wiki/Simple_polygon) states the following about Simple Polygons / Jordan Polygons:

> - A polygon encloses a region (called its interior) which always has a measurable area.
> - The line segments that make-up a polygon (called sides or edges) meet only at their endpoints, called vertices (singular: vertex) or less formally "corners".
> - Exactly two edges meet at each vertex.
> - The number of edges always equals the number of vertices.

However, the [lecture notes from an Illinois Computational Topology course](http://jeffe.cs.illinois.edu/teaching/comptop/chapters/01-simple-polygons.pdf) state the following:

> (...) A polygonal chain is closed if it has at least one edge and its first and last vertices coincide (that is, if
p_0 = p_n) and open otherwise.   (...)  A polygonal chain is simple if its vertices are distinct (except possibly
p_0 = p_n) and its edges intersect only at endpoints, or equivalently, if the corresponding path or
cycle is simple.

At a first thought, this seems to be in conflict with Wikipedia's definition. However, one should also realize that a  polygonal chain is not necessarily a polygon (I think only a closed polygonal chain is).

What does a LinearRing actually represent? A (closed?) polygonal chain?

Anyway, the correctness of topological definitions and class descriptions is probably not really important, it's just interesting.  

For now, the code should just be practical.

**Comment by dirkdokter** [comment]
> General remark. Note, that at some point we will start using NTS. This will impact these changes. In some situations you could check if NTS has the implementation you want to add. If not, then you could perhaps better add it as an extension method instead of a extra method to the geometry itself.

I agree that it would be good to switch to NTS at some point. We're just re-inventing the wheel at the moment.

Actually, in NTS they added a comment to LinearRing, which makes the definition more clear:
 https://github.com/NetTopologySuite/NetTopologySuite/blob/master/NetTopologySuite/Geometries/LinearRing.cs

> A LinearRing is a LineString which is both closed and simple. In other words, the first and last coordinate in the ring must be equal, and the interior of the ring must not self-intersect. Either orientation of the ring is allowed.
> - A ring must have either 0 or 4 or more points.
> - The first and last points must be equal (in 2D).
> - If these conditions are not met, the constructors throw an ArgumentException

**Comment by dirkdokter** [comment]
> From your other functionality I can see you are working on editing, because you are adding exactly the feature I need (I am also working on editing).

Yes, we already implemented editing functionality, and are using it successfully now. I still want to do some clean-up work and refactoring before pushing it.

It also uses a different structure for events (see #346), which makes is very #breaking.

infolayer

interctive_infolayer

**Comment by charlenni** [comment]
Very nice.

**Comment by pauldendulk** [comment]
@dirkdokter Thanks for the research :). About LinearRing.IsClosed. The guiding document for our geometry library and NTS is the Simple Feature specification by the OGC http://www.opengeospatial.org/standards/sfa.

It states at page 22:
> ⎯ IsClosed ( ): Integer — Returns 1 (TRUE) if this Curve is closed [StartPoint ( ) = EndPoint ( )]. 

This is about Curve, but LineString is a subclass of Curve and LinearRing is a subclass of LineString.

image

NTS and its java twin JTS have been developed to closely follow the OGC specifications.

**Comment by pauldendulk** [comment]
About rotation (it was in your other PR). It is not directly part of the geometry in the specification and in NTS, so for my own purpose I added an external extension method for rotation of any geometry:

```C#
        public static void Rotate(IGeometry geometry, double degrees, Point center)
        {
            foreach (var vertex in geometry.AllVertices())
            {
                Rotate(vertex, degrees, center);
            }
        }

        private static void Rotate(Point vertex, double degrees, Point center)
        {
            // translate this point back to the center
            var newX = vertex.X - center.X;
            var newY = vertex.Y - center.Y;

            // rotate the values
            var p = Algorithms.RotateClockwiseDegrees(newX, newY, degrees);

            // translate back to original reference frame
            vertex.X = p.X + center.X;
            vertex.Y = p.Y + center.Y;
        }
```

**Comment by pauldendulk** [comment]
About editing. Wow, I see you already made great progress. I have been working on very similar functionality. I will contact you for closer cooperation. There will probably be many edge cases to discuss. Also the user interaction design has many different options to choose from. Ideally I would like to have an interface that is UI independent on top of which different UIs can be implemented.

**Pull request merged**
