### PR TITLE
Enable invoke info on double tap

### PR DESCRIPTION
**Pull request by radderz**
Fix for #305 

Enabled double taps to also trigger info/widgets.

I think info/widgets needs to have a setting way to mention how many taps occured and a way for the info to return if it is handled. As double tap on the map is a common way to zoom which I may be implementing for issue #306. So if we have to have double tap info handling, then it should enable zoom if no item or widget was clicked, and some items may only be single or double click subscribed rather than both.

Any ideas on how we can improve the way the widget/info works to enable the above?

### CODE REVIEW

**Comment by charlenni** [comment]
I would prefer a solution, where each call of an event handler return a bool, if this event is handled or not. If it is handled, than no other event handler is called.

This should be done by a variable in the event arguments. If there is more than one handler attached to an event and we solve this by a function with return value, than only the last handler could return this value.

**Comment by pauldendulk** [comment]
@charlenni Is this based on other software where this is used?

**Comment by pauldendulk** [comment]
How badly do we need a beta of this?

**Comment by charlenni** [comment]
I find the problem when painting zoom buttons over map attribution. If you than touched on the buttons, the hyperlink was called, even it was drawn under the buttons.

With this in mind and radderz question, I searched for solutions. There are two: event handler with returning value or event argument mit return value. And if you don’t know, if more than one handler is attached to the event, the second is the better one.

**Comment by radderz** [comment]
@charlenni - Yes I was thinknig the same, I was thinking of adding both the number of taps that caused the info event, and also a handled boolean. Then if I implement double tap zoom, if it is not handled by the info then it can still do the zoom instead. I'll do this shortly and create a new pull request for this and you can see if it matches what you were thinking.

@pauldendulk - are we able to make it easier to create listed pre-release versions? Is there any reason not to create an auto publish mechanism off a trigger?

**Comment by pauldendulk** [comment]
I created an issue to improve pre-releases:
https://github.com/pauldendulk/Mapsui/issues/310

**Pull request merged**
